package com.example.admin.gsonproject;

public class Data
{
    public static String Profile = "{\n" +
            "  \"login\": \"aswain25\",\n" +
            "  \"id\": 37588012,\n" +
            "  \"avatar_url\": \"https://avatars3.githubusercontent.com/u/37588012?v=4\",\n" +
            "  \"gravatar_id\": \"\",\n" +
            "  \"url\": \"https://api.github.com/users/aswain25\",\n" +
            "  \"html_url\": \"https://github.com/aswain25\",\n" +
            "  \"followers_url\": \"https://api.github.com/users/aswain25/followers\",\n" +
            "  \"following_url\": \"https://api.github.com/users/aswain25/following{/other_user}\",\n" +
            "  \"gists_url\": \"https://api.github.com/users/aswain25/gists{/gist_id}\",\n" +
            "  \"starred_url\": \"https://api.github.com/users/aswain25/starred{/owner}{/repo}\",\n" +
            "  \"subscriptions_url\": \"https://api.github.com/users/aswain25/subscriptions\",\n" +
            "  \"organizations_url\": \"https://api.github.com/users/aswain25/orgs\",\n" +
            "  \"repos_url\": \"https://api.github.com/users/aswain25/repos\",\n" +
            "  \"events_url\": \"https://api.github.com/users/aswain25/events{/privacy}\",\n" +
            "  \"received_events_url\": \"https://api.github.com/users/aswain25/received_events\",\n" +
            "  \"type\": \"User\",\n" +
            "  \"site_admin\": false,\n" +
            "  \"name\": null,\n" +
            "  \"company\": null,\n" +
            "  \"blog\": \"\",\n" +
            "  \"location\": null,\n" +
            "  \"email\": null,\n" +
            "  \"hireable\": null,\n" +
            "  \"bio\": null,\n" +
            "  \"public_repos\": 15,\n" +
            "  \"public_gists\": 0,\n" +
            "  \"followers\": 0,\n" +
            "  \"following\": 0,\n" +
            "  \"created_at\": \"2018-03-20T15:12:00Z\",\n" +
            "  \"updated_at\": \"2018-04-07T00:02:45Z\"\n" +
            "}";
    public static String Repos = "[\n" +
            "  {\n" +
            "    \"id\": 128859654,\n" +
            "    \"name\": \"BroadcastRecieverProject\",\n" +
            "    \"full_name\": \"aswain25/BroadcastRecieverProject\",\n" +
            "    \"owner\": {\n" +
            "      \"login\": \"aswain25\",\n" +
            "      \"id\": 37588012,\n" +
            "      \"avatar_url\": \"https://avatars3.githubusercontent.com/u/37588012?v=4\",\n" +
            "      \"gravatar_id\": \"\",\n" +
            "      \"url\": \"https://api.github.com/users/aswain25\",\n" +
            "      \"html_url\": \"https://github.com/aswain25\",\n" +
            "      \"followers_url\": \"https://api.github.com/users/aswain25/followers\",\n" +
            "      \"following_url\": \"https://api.github.com/users/aswain25/following{/other_user}\",\n" +
            "      \"gists_url\": \"https://api.github.com/users/aswain25/gists{/gist_id}\",\n" +
            "      \"starred_url\": \"https://api.github.com/users/aswain25/starred{/owner}{/repo}\",\n" +
            "      \"subscriptions_url\": \"https://api.github.com/users/aswain25/subscriptions\",\n" +
            "      \"organizations_url\": \"https://api.github.com/users/aswain25/orgs\",\n" +
            "      \"repos_url\": \"https://api.github.com/users/aswain25/repos\",\n" +
            "      \"events_url\": \"https://api.github.com/users/aswain25/events{/privacy}\",\n" +
            "      \"received_events_url\": \"https://api.github.com/users/aswain25/received_events\",\n" +
            "      \"type\": \"User\",\n" +
            "      \"site_admin\": false\n" +
            "    },\n" +
            "    \"private\": false,\n" +
            "    \"html_url\": \"https://github.com/aswain25/BroadcastRecieverProject\",\n" +
            "    \"description\": null,\n" +
            "    \"fork\": false,\n" +
            "    \"url\": \"https://api.github.com/repos/aswain25/BroadcastRecieverProject\",\n" +
            "    \"forks_url\": \"https://api.github.com/repos/aswain25/BroadcastRecieverProject/forks\",\n" +
            "    \"keys_url\": \"https://api.github.com/repos/aswain25/BroadcastRecieverProject/keys{/key_id}\",\n" +
            "    \"collaborators_url\": \"https://api.github.com/repos/aswain25/BroadcastRecieverProject/collaborators{/collaborator}\",\n" +
            "    \"teams_url\": \"https://api.github.com/repos/aswain25/BroadcastRecieverProject/teams\",\n" +
            "    \"hooks_url\": \"https://api.github.com/repos/aswain25/BroadcastRecieverProject/hooks\",\n" +
            "    \"issue_events_url\": \"https://api.github.com/repos/aswain25/BroadcastRecieverProject/issues/events{/number}\",\n" +
            "    \"events_url\": \"https://api.github.com/repos/aswain25/BroadcastRecieverProject/events\",\n" +
            "    \"assignees_url\": \"https://api.github.com/repos/aswain25/BroadcastRecieverProject/assignees{/user}\",\n" +
            "    \"branches_url\": \"https://api.github.com/repos/aswain25/BroadcastRecieverProject/branches{/branch}\",\n" +
            "    \"tags_url\": \"https://api.github.com/repos/aswain25/BroadcastRecieverProject/tags\",\n" +
            "    \"blobs_url\": \"https://api.github.com/repos/aswain25/BroadcastRecieverProject/git/blobs{/sha}\",\n" +
            "    \"git_tags_url\": \"https://api.github.com/repos/aswain25/BroadcastRecieverProject/git/tags{/sha}\",\n" +
            "    \"git_refs_url\": \"https://api.github.com/repos/aswain25/BroadcastRecieverProject/git/refs{/sha}\",\n" +
            "    \"trees_url\": \"https://api.github.com/repos/aswain25/BroadcastRecieverProject/git/trees{/sha}\",\n" +
            "    \"statuses_url\": \"https://api.github.com/repos/aswain25/BroadcastRecieverProject/statuses/{sha}\",\n" +
            "    \"languages_url\": \"https://api.github.com/repos/aswain25/BroadcastRecieverProject/languages\",\n" +
            "    \"stargazers_url\": \"https://api.github.com/repos/aswain25/BroadcastRecieverProject/stargazers\",\n" +
            "    \"contributors_url\": \"https://api.github.com/repos/aswain25/BroadcastRecieverProject/contributors\",\n" +
            "    \"subscribers_url\": \"https://api.github.com/repos/aswain25/BroadcastRecieverProject/subscribers\",\n" +
            "    \"subscription_url\": \"https://api.github.com/repos/aswain25/BroadcastRecieverProject/subscription\",\n" +
            "    \"commits_url\": \"https://api.github.com/repos/aswain25/BroadcastRecieverProject/commits{/sha}\",\n" +
            "    \"git_commits_url\": \"https://api.github.com/repos/aswain25/BroadcastRecieverProject/git/commits{/sha}\",\n" +
            "    \"comments_url\": \"https://api.github.com/repos/aswain25/BroadcastRecieverProject/comments{/number}\",\n" +
            "    \"issue_comment_url\": \"https://api.github.com/repos/aswain25/BroadcastRecieverProject/issues/comments{/number}\",\n" +
            "    \"contents_url\": \"https://api.github.com/repos/aswain25/BroadcastRecieverProject/contents/{+path}\",\n" +
            "    \"compare_url\": \"https://api.github.com/repos/aswain25/BroadcastRecieverProject/compare/{base}...{head}\",\n" +
            "    \"merges_url\": \"https://api.github.com/repos/aswain25/BroadcastRecieverProject/merges\",\n" +
            "    \"archive_url\": \"https://api.github.com/repos/aswain25/BroadcastRecieverProject/{archive_format}{/ref}\",\n" +
            "    \"downloads_url\": \"https://api.github.com/repos/aswain25/BroadcastRecieverProject/downloads\",\n" +
            "    \"issues_url\": \"https://api.github.com/repos/aswain25/BroadcastRecieverProject/issues{/number}\",\n" +
            "    \"pulls_url\": \"https://api.github.com/repos/aswain25/BroadcastRecieverProject/pulls{/number}\",\n" +
            "    \"milestones_url\": \"https://api.github.com/repos/aswain25/BroadcastRecieverProject/milestones{/number}\",\n" +
            "    \"notifications_url\": \"https://api.github.com/repos/aswain25/BroadcastRecieverProject/notifications{?since,all,participating}\",\n" +
            "    \"labels_url\": \"https://api.github.com/repos/aswain25/BroadcastRecieverProject/labels{/name}\",\n" +
            "    \"releases_url\": \"https://api.github.com/repos/aswain25/BroadcastRecieverProject/releases{/id}\",\n" +
            "    \"deployments_url\": \"https://api.github.com/repos/aswain25/BroadcastRecieverProject/deployments\",\n" +
            "    \"created_at\": \"2018-04-10T02:10:23Z\",\n" +
            "    \"updated_at\": \"2018-04-10T02:10:56Z\",\n" +
            "    \"pushed_at\": \"2018-04-10T02:10:55Z\",\n" +
            "    \"git_url\": \"git://github.com/aswain25/BroadcastRecieverProject.git\",\n" +
            "    \"ssh_url\": \"git@github.com:aswain25/BroadcastRecieverProject.git\",\n" +
            "    \"clone_url\": \"https://github.com/aswain25/BroadcastRecieverProject.git\",\n" +
            "    \"svn_url\": \"https://github.com/aswain25/BroadcastRecieverProject\",\n" +
            "    \"homepage\": null,\n" +
            "    \"size\": 129,\n" +
            "    \"stargazers_count\": 0,\n" +
            "    \"watchers_count\": 0,\n" +
            "    \"language\": \"Java\",\n" +
            "    \"has_issues\": true,\n" +
            "    \"has_projects\": true,\n" +
            "    \"has_downloads\": true,\n" +
            "    \"has_wiki\": true,\n" +
            "    \"has_pages\": false,\n" +
            "    \"forks_count\": 0,\n" +
            "    \"mirror_url\": null,\n" +
            "    \"archived\": false,\n" +
            "    \"open_issues_count\": 0,\n" +
            "    \"license\": null,\n" +
            "    \"forks\": 0,\n" +
            "    \"open_issues\": 0,\n" +
            "    \"watchers\": 0,\n" +
            "    \"default_branch\": \"master\"\n" +
            "  },\n" +
            "  {\n" +
            "    \"id\": 127053197,\n" +
            "    \"name\": \"Calculator\",\n" +
            "    \"full_name\": \"aswain25/Calculator\",\n" +
            "    \"owner\": {\n" +
            "      \"login\": \"aswain25\",\n" +
            "      \"id\": 37588012,\n" +
            "      \"avatar_url\": \"https://avatars3.githubusercontent.com/u/37588012?v=4\",\n" +
            "      \"gravatar_id\": \"\",\n" +
            "      \"url\": \"https://api.github.com/users/aswain25\",\n" +
            "      \"html_url\": \"https://github.com/aswain25\",\n" +
            "      \"followers_url\": \"https://api.github.com/users/aswain25/followers\",\n" +
            "      \"following_url\": \"https://api.github.com/users/aswain25/following{/other_user}\",\n" +
            "      \"gists_url\": \"https://api.github.com/users/aswain25/gists{/gist_id}\",\n" +
            "      \"starred_url\": \"https://api.github.com/users/aswain25/starred{/owner}{/repo}\",\n" +
            "      \"subscriptions_url\": \"https://api.github.com/users/aswain25/subscriptions\",\n" +
            "      \"organizations_url\": \"https://api.github.com/users/aswain25/orgs\",\n" +
            "      \"repos_url\": \"https://api.github.com/users/aswain25/repos\",\n" +
            "      \"events_url\": \"https://api.github.com/users/aswain25/events{/privacy}\",\n" +
            "      \"received_events_url\": \"https://api.github.com/users/aswain25/received_events\",\n" +
            "      \"type\": \"User\",\n" +
            "      \"site_admin\": false\n" +
            "    },\n" +
            "    \"private\": false,\n" +
            "    \"html_url\": \"https://github.com/aswain25/Calculator\",\n" +
            "    \"description\": \"Week 2 assignment 1\",\n" +
            "    \"fork\": false,\n" +
            "    \"url\": \"https://api.github.com/repos/aswain25/Calculator\",\n" +
            "    \"forks_url\": \"https://api.github.com/repos/aswain25/Calculator/forks\",\n" +
            "    \"keys_url\": \"https://api.github.com/repos/aswain25/Calculator/keys{/key_id}\",\n" +
            "    \"collaborators_url\": \"https://api.github.com/repos/aswain25/Calculator/collaborators{/collaborator}\",\n" +
            "    \"teams_url\": \"https://api.github.com/repos/aswain25/Calculator/teams\",\n" +
            "    \"hooks_url\": \"https://api.github.com/repos/aswain25/Calculator/hooks\",\n" +
            "    \"issue_events_url\": \"https://api.github.com/repos/aswain25/Calculator/issues/events{/number}\",\n" +
            "    \"events_url\": \"https://api.github.com/repos/aswain25/Calculator/events\",\n" +
            "    \"assignees_url\": \"https://api.github.com/repos/aswain25/Calculator/assignees{/user}\",\n" +
            "    \"branches_url\": \"https://api.github.com/repos/aswain25/Calculator/branches{/branch}\",\n" +
            "    \"tags_url\": \"https://api.github.com/repos/aswain25/Calculator/tags\",\n" +
            "    \"blobs_url\": \"https://api.github.com/repos/aswain25/Calculator/git/blobs{/sha}\",\n" +
            "    \"git_tags_url\": \"https://api.github.com/repos/aswain25/Calculator/git/tags{/sha}\",\n" +
            "    \"git_refs_url\": \"https://api.github.com/repos/aswain25/Calculator/git/refs{/sha}\",\n" +
            "    \"trees_url\": \"https://api.github.com/repos/aswain25/Calculator/git/trees{/sha}\",\n" +
            "    \"statuses_url\": \"https://api.github.com/repos/aswain25/Calculator/statuses/{sha}\",\n" +
            "    \"languages_url\": \"https://api.github.com/repos/aswain25/Calculator/languages\",\n" +
            "    \"stargazers_url\": \"https://api.github.com/repos/aswain25/Calculator/stargazers\",\n" +
            "    \"contributors_url\": \"https://api.github.com/repos/aswain25/Calculator/contributors\",\n" +
            "    \"subscribers_url\": \"https://api.github.com/repos/aswain25/Calculator/subscribers\",\n" +
            "    \"subscription_url\": \"https://api.github.com/repos/aswain25/Calculator/subscription\",\n" +
            "    \"commits_url\": \"https://api.github.com/repos/aswain25/Calculator/commits{/sha}\",\n" +
            "    \"git_commits_url\": \"https://api.github.com/repos/aswain25/Calculator/git/commits{/sha}\",\n" +
            "    \"comments_url\": \"https://api.github.com/repos/aswain25/Calculator/comments{/number}\",\n" +
            "    \"issue_comment_url\": \"https://api.github.com/repos/aswain25/Calculator/issues/comments{/number}\",\n" +
            "    \"contents_url\": \"https://api.github.com/repos/aswain25/Calculator/contents/{+path}\",\n" +
            "    \"compare_url\": \"https://api.github.com/repos/aswain25/Calculator/compare/{base}...{head}\",\n" +
            "    \"merges_url\": \"https://api.github.com/repos/aswain25/Calculator/merges\",\n" +
            "    \"archive_url\": \"https://api.github.com/repos/aswain25/Calculator/{archive_format}{/ref}\",\n" +
            "    \"downloads_url\": \"https://api.github.com/repos/aswain25/Calculator/downloads\",\n" +
            "    \"issues_url\": \"https://api.github.com/repos/aswain25/Calculator/issues{/number}\",\n" +
            "    \"pulls_url\": \"https://api.github.com/repos/aswain25/Calculator/pulls{/number}\",\n" +
            "    \"milestones_url\": \"https://api.github.com/repos/aswain25/Calculator/milestones{/number}\",\n" +
            "    \"notifications_url\": \"https://api.github.com/repos/aswain25/Calculator/notifications{?since,all,participating}\",\n" +
            "    \"labels_url\": \"https://api.github.com/repos/aswain25/Calculator/labels{/name}\",\n" +
            "    \"releases_url\": \"https://api.github.com/repos/aswain25/Calculator/releases{/id}\",\n" +
            "    \"deployments_url\": \"https://api.github.com/repos/aswain25/Calculator/deployments\",\n" +
            "    \"created_at\": \"2018-03-27T22:32:21Z\",\n" +
            "    \"updated_at\": \"2018-03-28T04:17:51Z\",\n" +
            "    \"pushed_at\": \"2018-03-28T04:17:50Z\",\n" +
            "    \"git_url\": \"git://github.com/aswain25/Calculator.git\",\n" +
            "    \"ssh_url\": \"git@github.com:aswain25/Calculator.git\",\n" +
            "    \"clone_url\": \"https://github.com/aswain25/Calculator.git\",\n" +
            "    \"svn_url\": \"https://github.com/aswain25/Calculator\",\n" +
            "    \"homepage\": null,\n" +
            "    \"size\": 131,\n" +
            "    \"stargazers_count\": 0,\n" +
            "    \"watchers_count\": 0,\n" +
            "    \"language\": \"Java\",\n" +
            "    \"has_issues\": true,\n" +
            "    \"has_projects\": true,\n" +
            "    \"has_downloads\": true,\n" +
            "    \"has_wiki\": true,\n" +
            "    \"has_pages\": false,\n" +
            "    \"forks_count\": 0,\n" +
            "    \"mirror_url\": null,\n" +
            "    \"archived\": false,\n" +
            "    \"open_issues_count\": 0,\n" +
            "    \"license\": null,\n" +
            "    \"forks\": 0,\n" +
            "    \"open_issues\": 0,\n" +
            "    \"watchers\": 0,\n" +
            "    \"default_branch\": \"master\"\n" +
            "  },\n" +
            "  {\n" +
            "    \"id\": 127337903,\n" +
            "    \"name\": \"CelebrityDatabase\",\n" +
            "    \"full_name\": \"aswain25/CelebrityDatabase\",\n" +
            "    \"owner\": {\n" +
            "      \"login\": \"aswain25\",\n" +
            "      \"id\": 37588012,\n" +
            "      \"avatar_url\": \"https://avatars3.githubusercontent.com/u/37588012?v=4\",\n" +
            "      \"gravatar_id\": \"\",\n" +
            "      \"url\": \"https://api.github.com/users/aswain25\",\n" +
            "      \"html_url\": \"https://github.com/aswain25\",\n" +
            "      \"followers_url\": \"https://api.github.com/users/aswain25/followers\",\n" +
            "      \"following_url\": \"https://api.github.com/users/aswain25/following{/other_user}\",\n" +
            "      \"gists_url\": \"https://api.github.com/users/aswain25/gists{/gist_id}\",\n" +
            "      \"starred_url\": \"https://api.github.com/users/aswain25/starred{/owner}{/repo}\",\n" +
            "      \"subscriptions_url\": \"https://api.github.com/users/aswain25/subscriptions\",\n" +
            "      \"organizations_url\": \"https://api.github.com/users/aswain25/orgs\",\n" +
            "      \"repos_url\": \"https://api.github.com/users/aswain25/repos\",\n" +
            "      \"events_url\": \"https://api.github.com/users/aswain25/events{/privacy}\",\n" +
            "      \"received_events_url\": \"https://api.github.com/users/aswain25/received_events\",\n" +
            "      \"type\": \"User\",\n" +
            "      \"site_admin\": false\n" +
            "    },\n" +
            "    \"private\": false,\n" +
            "    \"html_url\": \"https://github.com/aswain25/CelebrityDatabase\",\n" +
            "    \"description\": null,\n" +
            "    \"fork\": false,\n" +
            "    \"url\": \"https://api.github.com/repos/aswain25/CelebrityDatabase\",\n" +
            "    \"forks_url\": \"https://api.github.com/repos/aswain25/CelebrityDatabase/forks\",\n" +
            "    \"keys_url\": \"https://api.github.com/repos/aswain25/CelebrityDatabase/keys{/key_id}\",\n" +
            "    \"collaborators_url\": \"https://api.github.com/repos/aswain25/CelebrityDatabase/collaborators{/collaborator}\",\n" +
            "    \"teams_url\": \"https://api.github.com/repos/aswain25/CelebrityDatabase/teams\",\n" +
            "    \"hooks_url\": \"https://api.github.com/repos/aswain25/CelebrityDatabase/hooks\",\n" +
            "    \"issue_events_url\": \"https://api.github.com/repos/aswain25/CelebrityDatabase/issues/events{/number}\",\n" +
            "    \"events_url\": \"https://api.github.com/repos/aswain25/CelebrityDatabase/events\",\n" +
            "    \"assignees_url\": \"https://api.github.com/repos/aswain25/CelebrityDatabase/assignees{/user}\",\n" +
            "    \"branches_url\": \"https://api.github.com/repos/aswain25/CelebrityDatabase/branches{/branch}\",\n" +
            "    \"tags_url\": \"https://api.github.com/repos/aswain25/CelebrityDatabase/tags\",\n" +
            "    \"blobs_url\": \"https://api.github.com/repos/aswain25/CelebrityDatabase/git/blobs{/sha}\",\n" +
            "    \"git_tags_url\": \"https://api.github.com/repos/aswain25/CelebrityDatabase/git/tags{/sha}\",\n" +
            "    \"git_refs_url\": \"https://api.github.com/repos/aswain25/CelebrityDatabase/git/refs{/sha}\",\n" +
            "    \"trees_url\": \"https://api.github.com/repos/aswain25/CelebrityDatabase/git/trees{/sha}\",\n" +
            "    \"statuses_url\": \"https://api.github.com/repos/aswain25/CelebrityDatabase/statuses/{sha}\",\n" +
            "    \"languages_url\": \"https://api.github.com/repos/aswain25/CelebrityDatabase/languages\",\n" +
            "    \"stargazers_url\": \"https://api.github.com/repos/aswain25/CelebrityDatabase/stargazers\",\n" +
            "    \"contributors_url\": \"https://api.github.com/repos/aswain25/CelebrityDatabase/contributors\",\n" +
            "    \"subscribers_url\": \"https://api.github.com/repos/aswain25/CelebrityDatabase/subscribers\",\n" +
            "    \"subscription_url\": \"https://api.github.com/repos/aswain25/CelebrityDatabase/subscription\",\n" +
            "    \"commits_url\": \"https://api.github.com/repos/aswain25/CelebrityDatabase/commits{/sha}\",\n" +
            "    \"git_commits_url\": \"https://api.github.com/repos/aswain25/CelebrityDatabase/git/commits{/sha}\",\n" +
            "    \"comments_url\": \"https://api.github.com/repos/aswain25/CelebrityDatabase/comments{/number}\",\n" +
            "    \"issue_comment_url\": \"https://api.github.com/repos/aswain25/CelebrityDatabase/issues/comments{/number}\",\n" +
            "    \"contents_url\": \"https://api.github.com/repos/aswain25/CelebrityDatabase/contents/{+path}\",\n" +
            "    \"compare_url\": \"https://api.github.com/repos/aswain25/CelebrityDatabase/compare/{base}...{head}\",\n" +
            "    \"merges_url\": \"https://api.github.com/repos/aswain25/CelebrityDatabase/merges\",\n" +
            "    \"archive_url\": \"https://api.github.com/repos/aswain25/CelebrityDatabase/{archive_format}{/ref}\",\n" +
            "    \"downloads_url\": \"https://api.github.com/repos/aswain25/CelebrityDatabase/downloads\",\n" +
            "    \"issues_url\": \"https://api.github.com/repos/aswain25/CelebrityDatabase/issues{/number}\",\n" +
            "    \"pulls_url\": \"https://api.github.com/repos/aswain25/CelebrityDatabase/pulls{/number}\",\n" +
            "    \"milestones_url\": \"https://api.github.com/repos/aswain25/CelebrityDatabase/milestones{/number}\",\n" +
            "    \"notifications_url\": \"https://api.github.com/repos/aswain25/CelebrityDatabase/notifications{?since,all,participating}\",\n" +
            "    \"labels_url\": \"https://api.github.com/repos/aswain25/CelebrityDatabase/labels{/name}\",\n" +
            "    \"releases_url\": \"https://api.github.com/repos/aswain25/CelebrityDatabase/releases{/id}\",\n" +
            "    \"deployments_url\": \"https://api.github.com/repos/aswain25/CelebrityDatabase/deployments\",\n" +
            "    \"created_at\": \"2018-03-29T19:26:13Z\",\n" +
            "    \"updated_at\": \"2018-03-29T19:26:48Z\",\n" +
            "    \"pushed_at\": \"2018-03-29T19:26:47Z\",\n" +
            "    \"git_url\": \"git://github.com/aswain25/CelebrityDatabase.git\",\n" +
            "    \"ssh_url\": \"git@github.com:aswain25/CelebrityDatabase.git\",\n" +
            "    \"clone_url\": \"https://github.com/aswain25/CelebrityDatabase.git\",\n" +
            "    \"svn_url\": \"https://github.com/aswain25/CelebrityDatabase\",\n" +
            "    \"homepage\": null,\n" +
            "    \"size\": 127,\n" +
            "    \"stargazers_count\": 0,\n" +
            "    \"watchers_count\": 0,\n" +
            "    \"language\": \"Java\",\n" +
            "    \"has_issues\": true,\n" +
            "    \"has_projects\": true,\n" +
            "    \"has_downloads\": true,\n" +
            "    \"has_wiki\": true,\n" +
            "    \"has_pages\": false,\n" +
            "    \"forks_count\": 0,\n" +
            "    \"mirror_url\": null,\n" +
            "    \"archived\": false,\n" +
            "    \"open_issues_count\": 0,\n" +
            "    \"license\": null,\n" +
            "    \"forks\": 0,\n" +
            "    \"open_issues\": 0,\n" +
            "    \"watchers\": 0,\n" +
            "    \"default_branch\": \"master\"\n" +
            "  }]";
}
